import { Double, Float } from 'react-native/Libraries/Types/CodegenTypes';

interface GeneralPractitionersField {
  name: string;
}

export interface GeneralPractitionersData {
  name: string;
  phone_one: string;
  address1: string;
  address2?: string;
  town: string;
  county: string;
  eircode: string;
  longitude: Double;
  lattitude: Double;
  distance?: any;
  website?: string;
  opening_hours?: string;
  general_practitioners_field: GeneralPractitionersField[];
}

export const gpp_data: GeneralPractitionersData[] = [
  {
    name: 'Gallagher Medical Practice',
    phone_one: '059 9133313',
    address1: '35c Dublin Street',
    town: 'Carlow Town',
    county: 'Carlow',
    eircode: 'R93 H9D0',
    longitude: -6.9310325,
    lattitude: 52.8384883,
    website: 'https://gallaghermedicalpractice.ie',
    opening_hours: 'Morning 8.30am to 12.30pm.\r\nAfternoon 2pm to 5pm.',
    general_practitioners_field: [
      { name: 'Azza Mohamed' },
      { name: 'Catherine Elliott' },
      { name: 'Clara Cannon' },
      { name: 'Niamh Gallagher' },
      { name: 'Nigel Solomon' },
      { name: 'Piroska Fazekas' },
      { name: 'Ronan Gallagher' },
      { name: 'Sannah Sithole' },
    ],
  },
  {
    name: 'Elm House Surgery',
    phone_one: '049 4331611',
    address1: 'Loughtee Business Park',
    town: 'Cootehill Road',
    county: 'Cavan',
    eircode: 'H12 V443',
    longitude: -7.3539,
    lattitude: 54.001202,
    website: 'https://www.elmsurgery.ie/html/index.html',
    general_practitioners_field: [
      { name: 'Domingo Ly Pen' },
      { name: 'Eamon McDwyer' },
      { name: 'Ese Nzewi' },
      { name: "Fanta O'Brien" },
      { name: 'Myra Varga' },
    ],
  },
  {
    name: 'Ardlea Medical Practice',
    phone_one: '065 6844455',
    address1: "79 Upper O'Connell Street",
    town: 'Ennis',
    county: 'Clare',
    eircode: 'V95 PD2N',
    longitude: -9.08454,
    lattitude: 52.85464,
    website: 'http://www.ardlea.net/',
    opening_hours:
      'Monday 9am to 5pm\r\nTuesday 9am to 5pm\r\nWednesday 9am to 2pm\r\nThursday 9am to 5pm (closed 1 to 2pm)\r\nFriday 9am to 5pm (closed 1 to 2pm)',
    general_practitioners_field: [{ name: 'John MacCarthy' }, { name: 'Sualeha Mujeeb' }],
  },
  {
    name: 'Millstreet Medical Centre',
    phone_one: '029 70124',
    address1: 'Killarney Road',
    town: ' Millstreet',
    county: 'Cork',
    eircode: 'P51 W9XE',
    longitude: -9.06905,
    lattitude: 52.06165,
    general_practitioners_field: [
      { name: "Chloe O'Sullivan" },
      { name: 'Con Breen' },
      { name: 'El\u00e9in Thompson' },
      { name: 'Mary Walsh-McCarthy' },
      { name: 'William Norton' },
    ],
  },
  {
    name: 'Stranorlar Primary Care Centre',
    phone_one: '074 9131344',
    address1: 'Pound Street',
    town: 'Stranorlar',
    county: 'Donegal',
    eircode: 'F93 D9HH',
    longitude: -7.7664,
    lattitude: 54.8047,
    opening_hours:
      'Monday 9am to 5pm\r\nTuesday 9am to 6pm\r\nWednesday 9am to 6pm\r\nThursday 9am to 6pm\r\nFriday 9am to 6pm\r\nSaturday 9am to 12pm\r\nSunday Closed',
    general_practitioners_field: [
      { name: 'Ciara McHugh' },
      { name: 'Eileen Coyne' },
      { name: 'Eoghan Hanley' },
      { name: 'John Sweeney' },
      { name: 'Magdalena Meges' },
      { name: 'Marcus Murphy' },
      { name: 'Martin Forkan' },
      { name: 'Rohan Modi' },
      { name: 'Ursula Keegan' },
    ],
  },
  {
    name: 'Castle Medical Centre',
    phone_one: '091 767449',
    address1: 'Unit 4 Centrepoint',
    address2: ' Liosban Industrial Estate',
    town: ' Tuam Road',
    county: 'Galway',
    eircode: ' H91 Y61X',
    longitude: -9.03286,
    lattitude: 53.28667,
    general_practitioners_field: [
      { name: "Aine O'Connell" },
      { name: 'Amir Alsaffar' },
      { name: 'David Hill' },
      { name: 'Deon Knight' },
      { name: 'Elizabeth Chambers' },
      { name: 'Emma Waldron' },
      { name: 'Margaret Cashman' },
      { name: 'Maria Lewis (Mannion)' },
      { name: 'Marie Dillon' },
      { name: 'Mary Egan' },
      { name: 'Susan Duffy' },
    ],
  },
  {
    name: 'The Medical Centre',
    phone_one: '064 6641333',
    address1: 'Railway Road',
    town: 'Kenmare',
    county: 'Kerry',
    eircode: 'V93 Y02R',
    longitude: -9.57965,
    lattitude: 51.885,
    opening_hours:
      'Monday 9am to 5pm\r\nTuesday 9am to 5pm\r\nWednesday 9am to 5pm\r\nThursday 9am to 5pm\r\nFriday 9am to 5pm\r\nSaturday Closed\r\nSunday Closed',
    general_practitioners_field: [
      { name: 'Aideen Russell' },
      { name: 'Anton Wauters' },
      { name: "Bernadette O'Drisceoil" },
      { name: 'Hilda Crushell' },
      { name: 'Maria Calnan' },
      { name: 'Mary Quille' },
      { name: "Ruadhrui O'Drisceoil" },
      { name: 'Ryan Say' },
    ],
  },
  {
    name: 'Glen Easton Medical Centre',
    phone_one: '01 6060061',
    address1: 'Glen Easton Shopping Centre',
    address2: 'Glen Easton',
    town: 'Leixlip',
    county: 'Kildare',
    eircode: 'W23 P061',
    longitude: -6.51723,
    lattitude: 53.365589,
    website: 'https://www.myleixlipdoctor.ie',
    opening_hours:
      'Monday 8.30am to 5.30pm\r\nTuesday 8.30am to 5.30pm\r\nWednesday 8.30am to 5.30pm\r\nThursday 8.30am to 5.30pm\r\nFriday 8.30am to 5.30pm\r\nSaturday Closed\r\nSunday Closed',
    general_practitioners_field: [
      { name: 'David Hanlon' },
      { name: 'Martina Dillane' },
      { name: 'Mary Hanlon' },
    ],
  },
  {
    name: 'Gowran Medical & Travel Health',
    phone_one: '056 7726116',
    address1: 'Gowran Health Centre',
    address2: 'Main Street',
    town: 'Gowran',
    county: 'Kilkenny',
    eircode: 'R95 PYW6',
    lattitude: 52.62961,
    longitude: -7.06354,
    website: 'http://www.gowranmed.com/',
    opening_hours:
      'Monday 9am to 11am, 2pm to 5pm\r\nTuesday 2pm to 5pm\r\nWednesday 9am to 11am, 2pm to 5pm\r\nThursday 9am to 12pm\r\nFriday 11am to 12.30pm, 2.30pm to 4pm\r\nSaturday Closed\r\nSunday Closed',
    general_practitioners_field: [
      { name: 'Alaa Ashour' },
      { name: "Clare O'Brien" },
      { name: 'Luke Gallagher' },
    ],
  },
  {
    name: 'Medi Centre',
    phone_one: '057 8623138',
    address1: 'Link Road',
    town: 'Portarlington',
    county: 'Laois',
    eircode: 'R32 PY5N',
    longitude: -7.18732,
    lattitude: 53.15995,
    website: 'http://medicentre.ie',
    opening_hours:
      'Monday 9am to 5pm\r\nTuesday 9am to 5pm\r\nWednesday 9am to 5pm\r\nThursday 9am to 5pm\r\nFriday 9am to 5pm\r\nSaturday Closed\r\nSunday Closed',
    general_practitioners_field: [
      { name: 'Cyril Okpuno' },
      { name: 'Fergus McKeagney' },
      { name: "Frank O'Hara" },
      { name: 'Ines Dekester' },
      { name: 'Judith Murray' },
      { name: 'Mousumi Dunne' },
      { name: 'Olive Strumble' },
      { name: 'Shonagh Mooney' },
    ],
  },
  {
    name: 'Carrigallen Health Centre',
    phone_one: '049 4339797',
    address1: 'Clooncorick',
    town: ' Carrigallen',
    county: 'Leitrim',
    eircode: 'H12 K5N7',
    longitude: -7.63932,
    lattitude: 53.97739,
    general_practitioners_field: [{ name: 'Antoinette Gregan' }, { name: 'Jason Fallon' }],
  },
  {
    name: 'Westbury Medical Centre',
    phone_one: '068 42271',
    address1: 'Athea Upper',
    town: 'Athea',
    county: 'Limerick',
    eircode: 'V94 997A',
    longitude: -9.29261,
    lattitude: 52.46101,
    opening_hours:
      'Monday 9am to 6pm\r\nTuesday 9am to 6pm\r\nWednesday 9am to 6pm\r\nThursday 9am to 6pm\r\nFriday 9am to 6pm\r\nSaturday Closed\r\nSunday Closed',
    general_practitioners_field: [
      { name: "Brendan O'Connell" },
      { name: 'Brid Wallace' },
      { name: 'Eoin Ryan' },
      { name: 'Kieran Murphy' },
      { name: 'Maire Crowley' },
      { name: 'Mary Barry' },
      { name: 'Patricia Kennelly' },
    ],
  },
  {
    name: 'The Atrium Medical Practice ',
    phone_one: '043 3345182',
    address1: '1 College Park',
    town: ' Longford',
    county: 'Longford',
    eircode: 'N39 Y6C9',
    longitude: -7.78756,
    lattitude: 53.73048,
    general_practitioners_field: [
      { name: 'Celine McHugh' },
      { name: 'Jennifer Clarke' },
      { name: 'Jude McEntire' },
      { name: 'Judy Kirk' },
      { name: 'Mairead Greene' },
      { name: 'Reem Saied' },
      { name: 'Saddig Dauki' },
      { name: 'Stephen Tselapedi' },
      { name: 'Zahir Mohamed' },
    ],
  },
  {
    name: 'Number 47 Medical Practice',
    phone_one: '041 9837501 ',
    address1: '47 Fair Street',
    town: ' Drogheda',
    county: 'Louth',
    eircode: 'A92 Y62H',
    longitude: -6.35488,
    lattitude: 53.716431,
    general_practitioners_field: [
      { name: 'Alison Hoey' },
      { name: 'Brian Hollins' },
      { name: 'Carmel Hutcheson' },
      { name: 'Conor MacMahon' },
      { name: 'Easentheren Naidoo' },
      { name: 'Mahvish Zeeshan' },
      { name: 'Paul Finegan' },
      { name: 'Sadaf Amir' },
      { name: 'Yvonne Sweeney' },
    ],
  },
  {
    name: 'Kilkelly Medical Centre',
    phone_one: '094 9367056',
    address1: 'Ballaghadereen Road',
    town: 'Kilkelly',
    county: 'Mayo',
    eircode: 'F35 A092',
    longitude: -8.84696,
    lattitude: 53.87213,
    general_practitioners_field: [{ name: 'Clair Ward' }],
  },
  {
    name: 'Summerhill Medical Centre',
    phone_one: '046 9557004',
    address1: 'Summerhill Primary Care Centre',
    address2: 'New Road',
    town: ' Summerhill',
    county: 'Meath',
    eircode: 'A83 V252',
    longitude: -6.73788,
    lattitude: 53.482899,
    general_practitioners_field: [
      { name: 'Ailsa McGarry' },
      { name: 'Billy Storan' },
      { name: 'Brendan Crosbie' },
      { name: 'Fidelma Ofor' },
      { name: 'Joseph Clarke' },
      { name: 'Katherine Lydon' },
      { name: 'Mary Taaffe' },
      { name: 'Michael Collins' },
    ],
  },
  {
    name: 'Health Care Unit Ballybay',
    phone_one: '042 9741095',
    address1: 'Main Street',
    town: ' Ballybay',
    county: 'Monaghan',
    eircode: 'A75 DY07',
    longitude: -6.90297,
    lattitude: 54.1287,
    general_practitioners_field: [
      { name: 'Andries Barnard' },
      { name: 'Anna Venter' },
      { name: 'Brian Norton' },
      { name: 'John Crummie' },
      { name: 'Michael Keyes' },
      { name: 'Rania Ali' },
    ],
  },
  {
    name: 'Banagher Health Centre',
    phone_one: '057 9151247',
    address1: 'Primary Care Centre',
    town: ' Banagher',
    county: 'Offaly',
    eircode: 'R42 XW40',
    longitude: -7.98706,
    lattitude: 53.18378,
    general_practitioners_field: [
      { name: 'Abir Abuazza' },
      { name: 'Francois Vorster' },
      { name: 'Johannes Welman' },
      { name: 'Mary Harkins' },
      { name: 'Michael Steenkamp' },
      { name: 'Niamh Barrett' },
      { name: 'Shane Carroll' },
      { name: 'Volha Samafalava' },
      { name: 'Warren Deeves' },
    ],
  },
];
